#!
# -*- coding: utf-8 -*-

"""
╔════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                    ║
║   Copyright (c) 2020 https://prrvchr.github.io                                     ║
║                                                                                    ║
║   Permission is hereby granted, free of charge, to any person obtaining            ║
║   a copy of this software and associated documentation files (the "Software"),     ║
║   to deal in the Software without restriction, including without limitation        ║
║   the rights to use, copy, modify, merge, publish, distribute, sublicense,         ║
║   and/or sell copies of the Software, and to permit persons to whom the Software   ║
║   is furnished to do so, subject to the following conditions:                      ║
║                                                                                    ║
║   The above copyright notice and this permission notice shall be included in       ║
║   all copies or substantial portions of the Software.                              ║
║                                                                                    ║
║   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,                  ║
║   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES                  ║
║   OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.        ║
║   IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY             ║
║   CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,             ║
║   TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE       ║
║   OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                    ║
║                                                                                    ║
╚════════════════════════════════════════════════════════════════════════════════════╝
"""

from com.sun.star.sdbc.ColumnValue import NO_NULLS
from com.sun.star.sdbc.ColumnValue import NULLABLE

import traceback


def getStaticTables():
    return {'Tables':      {'CatalogName': 'PUBLIC',
                            'SchemaName':  'PUBLIC',
                            'Type':        'TEXT TABLE',
                            'Columns': ({'Name': 'Table',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'CatalogName',
                                         'TypeName': 'VARCHAR',
                                         'Type': 12,
                                         'Scale': 100,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'SchemaName',
                                         'TypeName': 'VARCHAR',
                                         'Type': 12,
                                         'Scale': 100,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'Name',
                                         'TypeName': 'VARCHAR',
                                         'Type': 12,
                                         'Scale': 100,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'Identity',
                                         'TypeName': 'SMALLINT',
                                         'Type': 5,
                                         'IsNullable': NULLABLE,
                                         'DefaultValue': 'NULL'},
                                        {'Name': 'View',
                                         'TypeName': 'BOOLEAN',
                                         'Type': 16,
                                         'IsNullable': NULLABLE,
                                         'DefaultValue': 'FALSE'}),
                            'PrimaryKeys': ('Table', )},
            'Columns':     {'CatalogName': 'PUBLIC',
                            'SchemaName':  'PUBLIC',
                            'Type':        'TEXT TABLE',
                            'Columns': ({'Name': 'Column',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'Name',
                                         'TypeName': 'VARCHAR',
                                         'Type': 12,
                                         'Scale': 100,
                                         'IsNullable': NO_NULLS}),
                            'PrimaryKeys': ('Column', )},
            'TableColumn': {'CatalogName': 'PUBLIC',
                            'SchemaName':  'PUBLIC',
                            'Type':        'TEXT TABLE',
                            'Columns': ({'Name': 'Table',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'Column',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'TypeName',
                                         'TypeName': 'VARCHAR',
                                         'Type': 12,
                                         'Scale': 100,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'Type',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'Scale',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NULLABLE,
                                         'DefaultValue': 'NULL'},
                                        {'Name': 'IsNullable',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NO_NULLS,
                                         'DefaultValue': '0'},
                                        {'Name': 'DefaultValue',
                                         'TypeName': 'VARCHAR',
                                         'Type': 12,
                                         'Scale': 100,
                                         'IsNullable': NULLABLE,
                                         'DefaultValue': 'NULL'},
                                        {'Name': 'IsRowVersion',
                                         'TypeName': 'BOOLEAN',
                                         'Type': 16,
                                         'IsNullable': NULLABLE,
                                         'DefaultValue': 'NULL'},
                                        {'Name': 'Primary',
                                         'TypeName': 'BOOLEAN',
                                         'Type': 16,
                                         'IsNullable': NULLABLE,
                                         'DefaultValue': 'NULL'}),
                            'PrimaryKeys': ('Table', 'Column')},
            'ForeignKeys': {'CatalogName': 'PUBLIC',
                            'SchemaName':  'PUBLIC',
                            'Type':        'TEXT TABLE',
                            'Columns': ({'Name': 'Table',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'Column',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'ReferencedTable',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'RelatedColumn',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'UpdateRule',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'DeleteRule',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NO_NULLS})},
            'Indexes':     {'CatalogName': 'PUBLIC',
                            'SchemaName':  'PUBLIC',
                            'Type':        'TEXT TABLE',
                            'Columns': ({'Name': 'Index',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'Table',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'Column',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'Unique',
                                         'TypeName': 'BOOLEAN',
                                         'Type': 16,
                                         'IsNullable': NO_NULLS,
                                         'DefaultValue': 'TRUE'})},
            'Privileges':  {'CatalogName': 'PUBLIC',
                            'SchemaName':  'PUBLIC',
                            'Type':        'TEXT TABLE',
                            'Columns': ({'Name': 'Table',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'Column',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NULLABLE,
                                         'DefaultValue': 'NULL'},
                                        {'Name': 'Role',
                                         'TypeName': 'VARCHAR',
                                         'Type': 12,
                                         'Scale': 100,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'Privilege',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NO_NULLS})},
            'Settings':    {'CatalogName': 'PUBLIC',
                            'SchemaName':  'PUBLIC',
                            'Type':        'TEXT TABLE',
                            'Columns': ({'Name': 'Id',
                                         'TypeName': 'INTEGER',
                                         'Type': 4,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'Name',
                                         'TypeName': 'VARCHAR',
                                         'Type': 12,
                                         'Scale': 100,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'Value1',
                                         'TypeName': 'VARCHAR',
                                         'Type': 12,
                                         'Scale': 100,
                                         'IsNullable': NO_NULLS},
                                        {'Name': 'Value2',
                                         'TypeName': 'VARCHAR',
                                         'Type': 12,
                                         'Scale': 100,
                                         'IsNullable': NULLABLE,
                                         'DefaultValue': 'NULL'},
                                        {'Name': 'Value3',
                                         'TypeName': 'VARCHAR',
                                         'Type': 12,
                                         'Scale': 100,
                                         'IsNullable': NULLABLE,
                                         'DefaultValue': 'NULL'}),
                            'PrimaryKeys': ('Id', )}}

def getUniqueIndexes():
    return (('PUBLIC.PUBLIC.Tables',  True, ('CatalogName', 'SchemaName', 'Name')),
            ('PUBLIC.PUBLIC.Columns', True, ('Name', )))

def getForeignKeys():
    return (('PUBLIC.PUBLIC.TableColumn', 'Table',  'PUBLIC.PUBLIC.Tables',  'Table',  0, 0),
            ('PUBLIC.PUBLIC.TableColumn', 'Column', 'PUBLIC.PUBLIC.Columns', 'Column', 0, 0),
            ('PUBLIC.PUBLIC.ForeignKeys', 'Table',  'PUBLIC.PUBLIC.Tables',  'Table',  0, 0),
            ('PUBLIC.PUBLIC.ForeignKeys', 'Column', 'PUBLIC.PUBLIC.Columns', 'Column', 0, 0),
            ('PUBLIC.PUBLIC.Indexes',     'Table',  'PUBLIC.PUBLIC.Tables',  'Table',  0, 0),
            ('PUBLIC.PUBLIC.Indexes',     'Column', 'PUBLIC.PUBLIC.Columns', 'Column', 0, 0),
            ('PUBLIC.PUBLIC.Privileges',  'Table',  'PUBLIC.PUBLIC.Tables',  'Table',  0, 0),
            ('PUBLIC.PUBLIC.Privileges',  'Column', 'PUBLIC.PUBLIC.Columns', 'Column', 0, 0))

