#ifndef __com_sun_star_sdbc_XRestDataSource_idl__
#define __com_sun_star_sdbc_XRestDataSource_idl__

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/sdbc/XRestProvider.idl>
#include <com/sun/star/auth/XRestKeyMap.idl>
#include <com/sun/star/sdbc/XConnection.idl>
#include <com/sun/star/sdbc/XPreparedStatement.idl>
#include <com/sun/star/beans/Optional.idl>
#include <com/sun/star/logging/XLogger.idl>

module com { module sun { module star { module sdbc {

interface XRestDataSource: com::sun::star::uno::XInterface
{

    any getWarnings();
    void clearWarnings();
    ::com::sun::star::uno::XInterface getUser([in] string Name,
                                              [in] string Password);

    [attribute, readonly] ::com::sun::star::sdbc::XRestProvider Provider;
    [attribute, readonly] ::com::sun::star::uno::XInterface Connection;

};

}; }; }; };

#endif
