#ifndef __com_sun_star_sdbc_XRestUser_idl__
#define __com_sun_star_sdbc_XRestUser_idl__

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/auth/XRestKeyMap.idl>
#include <com/sun/star/sdbc/XConnection.idl>
#include <com/sun/star/sdbc/XRestProvider.idl>
#include <com/sun/star/sdbc/XDataSource.idl>

module com { module sun { module star { module sdbc {

interface XRestUser: com::sun::star::uno::XInterface
{

    ::com::sun::star::sdbc::XConnection getConnection([in] ::com::sun::star::sdbc::XDataSource DataSource,
                                                      [in] string Password);

    sequence<string> getCredential([in] string Password);

    any getWarnings();
    void clearWarnings();

    [attribute, readonly] ::com::sun::star::uno::XInterface Request;
    [attribute, readonly] ::com::sun::star::sdbc::XRestProvider Provider;
    [attribute] ::com::sun::star::auth::XRestKeyMap MetaData;
    [attribute, readonly] sequence<string> Fields;
    [attribute, readonly] long People;
    [attribute, readonly] long Group;
    [attribute, readonly] string Resource;
    [attribute, readonly] string Account;
    [attribute, readonly] string PeopleSync;
    [attribute, readonly] string GroupSync;

};


}; }; }; };

#endif
