/*
╔════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                    ║
║   Copyright (c) 2020-25 https://prrvchr.github.io                                  ║
║                                                                                    ║
║   Permission is hereby granted, free of charge, to any person obtaining            ║
║   a copy of this software and associated documentation files (the "Software"),     ║
║   to deal in the Software without restriction, including without limitation        ║
║   the rights to use, copy, modify, merge, publish, distribute, sublicense,         ║
║   and/or sell copies of the Software, and to permit persons to whom the Software   ║
║   is furnished to do so, subject to the following conditions:                      ║
║                                                                                    ║
║   The above copyright notice and this permission notice shall be included in       ║
║   all copies or substantial portions of the Software.                              ║
║                                                                                    ║
║   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,                  ║
║   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES                  ║
║   OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.        ║
║   IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY             ║
║   CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,             ║
║   TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE       ║
║   OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                    ║
║                                                                                    ║
╚════════════════════════════════════════════════════════════════════════════════════╝
 */

#ifndef __com_sun_star_rest_HTTPStatusCode_idl__
#define __com_sun_star_rest_HTTPStatusCode_idl__


module com {  module sun {  module star {  module rest {

constants HTTPStatusCode
{


    /** Informational.
    */
    const long CONTINUE                     = 100;
    const long SWITCH_PROTOCOL              = 101;
    const long PROCESSING                   = 102;
    const long CHECKPOINT                   = 103;
    const long URI_TOO_LONG                 = 122;
    const long OK                           = 200;
    const long CREATED                      = 201;
    const long ACCEPTED                     = 202;
    const long NON_AUTHORITATIVE_INFO       = 203;
    const long NO_CONTENT                   = 204;
    const long RESET_CONTENT                = 205;
    const long PARTIAL                      = 206;
    const long MULTI_STATUS                 = 207;
    const long ALREADY_REPORTED             = 208;
    const long IM_USED                      = 226;

    /**  Redirection.
    */
    const long MULTIPLE_CHOICES             = 300;
    const long MOVED                        = 301;
    const long FOUND                        = 302;
    const long OTHER                        = 303;
    const long NOT_MODIFIED                 = 304;
    const long USE_PROXY                    = 305;
    const long SWITCH_PROXY                 = 306;
    const long TEMPORARY_REDIRECT           = 307;
    const long PERMANENT_REDIRECT           = 308;

    /** Client Error.
    */
    const long BAD_REQUEST                  = 400;
    const long UNAUTHORIZED                 = 401;
    const long PAYEMENT_REQUIRED            = 402;
    const long FORBIDDEN                    = 403;
    const long NOT_FOUND                    = 404;
    const long NOT_ALLOWED                  = 405;
    const long NOT_ACCEPTABLE               = 406;
    const long PROXY_AUTH                   = 407;
    const long TIMEOUT                      = 408;
    const long CONFLICT                     = 409;
    const long GONE                         = 410;
    const long LENGTH_REQUIRED              = 411;
    const long PRECONDITION_FAILED          = 412;
    const long REQUEST_ENTITY_TOO_LARGE     = 413;
    const long REQUEST_MEDIA_TOO_LARGE      = 414;
    const long UNSUPPORTED_MEDIA            = 415;
    const long RANGE_NOT_SATISFIABLE        = 416;
    const long EXPECTATION_FAILED           = 417;
    const long TEAPOT                       = 418;
    const long MISDIRECTED_REQUEST          = 421;
    const long UNPROCESSABLE                = 422;
    const long LOCKED                       = 423;
    const long DEPENDENCY                   = 424;
    const long UNORDERED                    = 425;
    const long UPGRADE                      = 426;
    const long PRECONDITION_REQUIRED        = 428;
    const long TOO_MANY                     = 429;
    const long FIELDS_TOO_LARGE             = 431;
    const long NO_RESPONSE                  = 444;
    const long RETRY                        = 449;
    const long PARENTAL_REASONS             = 450;
    const long LEGAL_REASONS                = 451;
    const long CLIENT_CLOSED                = 499;

    /** Server Error.
    */
    const long SERVER_ERROR                 = 500;
    const long NOT_IMPLEMENTED              = 501;
    const long BAD_GATEWAY                  = 502;
    const long UNAVAILABLE                  = 503;
    const long GATEWAY_TIMEOUT              = 504;
    const long HTTP_VERSION                 = 505;
    const long VARIANT_ALSO_NEGOTIATES      = 506;
    const long INSUFFICIENT_STORAGE         = 507;
    const long BANDWIDTH                    = 509;
    const long NOT_EXTENTED                 = 510;
    const long NETWORK_AUTH                 = 511;


};

}; }; }; };

#endif
