#ifndef __com_sun_star_auth_XOAuth2Service_idl__
#define __com_sun_star_auth_XOAuth2Service_idl__

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/auth/RestRequestParameter.idl>
#include <com/sun/star/auth/XRestKeyMap.idl>
#include <com/sun/star/auth/XRestRequest.idl>
#include <com/sun/star/auth/XRestEnumeration.idl>
#include <com/sun/star/beans/Optional.idl>
#include <com/sun/star/io/XInputStream.idl>
#include <com/sun/star/io/XOutputStream.idl>
#include <com/sun/star/container/XEnumeration.idl>
#include <com/sun/star/sdbc/XConnection.idl>
#include <com/sun/star/logging/XLogger.idl>

module com { module sun { module star { module auth {

interface XOAuth2Service: com::sun::star::uno::XInterface
{

    any getWarnings();
    void clearWarnings();

    boolean isOnLine();
    boolean isOffLine([in] string Host);

    boolean initializeUrl([in] string ResourceUrl);
    boolean initializeSession([in] string ResourceUrl,
                              [in] string UserName);

    boolean getAuthorization([in] string ResourceUrl,
                             [in] string UserName,
                             [in] boolean AutoClose);

    string getToken([in] string Format);

    short getSessionMode([in] string Host);

    ::com::sun::star::auth::XRestKeyMap getKeyMap();

    ::com::sun::star::beans::Optional<::com::sun::star::auth::XRestKeyMap> execute([in] RestRequestParameter Parameter);

    ::com::sun::star::auth::XRestEnumeration getEnumerator([in] RestRequestParameter Parameter);

    ::com::sun::star::auth::XRestRequest getRequest([in] RestRequestParameter Parameter,
                                                    [in] ::com::sun::star::uno::XInterface Parser);

    ::com::sun::star::auth::XRestEnumeration getEnumeration([in] RestRequestParameter Parameter,
                                                            [in] ::com::sun::star::uno::XInterface Parser);

    ::com::sun::star::auth::XRestEnumeration getIterator([in] RestRequestParameter Parameter,
                                                         [in] ::com::sun::star::uno::XInterface Parser);

    ::com::sun::star::io::XInputStream getInputStream([in] RestRequestParameter Parameter,
                                                      [in] long Chunk,
                                                      [in] long Buffer);

    ::com::sun::star::uno::XInterface getUploader([in] long Chunk,
                                                  [in] string Url,
                                                  [in] ::com::sun::star::uno::XInterface CallBack);

    [attribute, readonly] ::com::sun::star::uno::XInterface Setting;
    [attribute, readonly] ::com::sun::star::uno::XInterface Session;
    [attribute, readonly] string ResourceUrl;
    [attribute, readonly] string ProviderName;
    [attribute, readonly] string UserName;
    [attribute, readonly] any Timeout;
    [attribute] string Error;

};


}; }; }; };

#endif
