#ifndef __com_sun_star_auth_XRestDataParser_idl__
#define __com_sun_star_auth_XRestDataParser_idl__

#include <com/sun/star/uno/XInterface.idl>

module com { module sun { module star { module auth {

interface XRestDataParser: com::sun::star::uno::XInterface
{

    any parseResponse([in] any Response);

    [attribute, readonly] string DataType;

};


}; }; }; };

#endif
