/*
╔════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                    ║
║   Copyright (c) 2020 https://prrvchr.github.io                                     ║
║                                                                                    ║
║   Permission is hereby granted, free of charge, to any person obtaining            ║
║   a copy of this software and associated documentation files (the "Software"),     ║
║   to deal in the Software without restriction, including without limitation        ║
║   the rights to use, copy, modify, merge, publish, distribute, sublicense,         ║
║   and/or sell copies of the Software, and to permit persons to whom the Software   ║
║   is furnished to do so, subject to the following conditions:                      ║
║                                                                                    ║
║   The above copyright notice and this permission notice shall be included in       ║
║   all copies or substantial portions of the Software.                              ║
║                                                                                    ║
║   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,                  ║
║   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES                  ║
║   OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.        ║
║   IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY             ║
║   CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,             ║
║   TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE       ║
║   OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                    ║
║                                                                                    ║
╚════════════════════════════════════════════════════════════════════════════════════╝
 */

#ifndef __com_sun_star_auth_XOAuth2Service_idl__
#define __com_sun_star_auth_XOAuth2Service_idl__

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/auth/RefreshTokenException.idl>
#include <com/sun/star/rest/RequestException.idl>
#include <com/sun/star/rest/XRequestResponse.idl>
#include <com/sun/star/rest/XRequestParameter.idl>
#include <com/sun/star/io/XInputStream.idl>
#include <com/sun/star/awt/XWindowPeer.idl>

module com { module sun { module star { module auth {

interface XOAuth2Service: com::sun::star::uno::XInterface
{

    boolean isOnLine();
    boolean isOffLine([in] string Host);

    boolean initializeUrl([in] string ResourceUrl);
    boolean initializeSession([in] string ResourceUrl,
                              [in] string UserName);

    boolean getAuthorization([in] string ResourceUrl,
                             [in] string UserName,
                             [in] boolean AutoClose,
                             [in] com::sun::star::awt::XWindowPeer Parent);

    string getToken([in] string Format)
                    raises(com::sun::star::auth::RefreshTokenException);

    short getSessionMode([in] string Host);

    string unquoteUrl([in] string Url);

    com::sun::star::rest::XRequestParameter getRequestParameter([in] string Name);

    com::sun::star::rest::XRequestResponse execute([in] com::sun::star::rest::XRequestParameter Parameter)
                                           raises(com::sun::star::rest::RequestException);

    com::sun::star::io::XInputStream getInputStream([in] com::sun::star::rest::XRequestParameter Parameter,
                                                    [in] long Chunk,
                                                    [in] boolean Decode)
                                     raises(com::sun::star::rest::RequestException);

    boolean download([in] com::sun::star::rest::XRequestParameter Parameter,
                     [in] string Url,
                     [in] long Chunk,
                     [in] short Retry,
                     [in] short Delay)
            raises(com::sun::star::rest::RequestException);

    boolean upload([in] com::sun::star::rest::XRequestParameter Parameter,
                   [in] string Url,
                   [in] long Chunk,
                   [in] short Retry,
                   [in] short Delay)
            raises(com::sun::star::rest::RequestException);

    [attribute, readonly] string ResourceUrl;
    [attribute, readonly] string ProviderName;
    [attribute, readonly] string UserName;
    [attribute, readonly] sequence<short> Timeout;


};


}; }; }; };

#endif
