#ifndef __com_sun_star_ucb_AuthenticationRequest2_idl__
#define __com_sun_star_ucb_AuthenticationRequest2_idl__

#include <com/sun/star/task/ClassifiedInteractionRequest.idl>

module com {  module sun {  module star {  module ucb {

exception AuthenticationRequest2: com::sun::star::task::ClassifiedInteractionRequest
{

    string ServerName;
    string Diagnostic;
    boolean HasRealm;
    string Realm;
    boolean HasUserName;
    string UserName;
    boolean HasPassword;
    string Password;
    boolean HasAccount;
    string Account;
    sequence<any> args;

};

}; }; }; };

#endif
