/*
╔════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                    ║
║   Copyright (c) 2020-25 https://prrvchr.github.io                                  ║
║                                                                                    ║
║   Permission is hereby granted, free of charge, to any person obtaining            ║
║   a copy of this software and associated documentation files (the "Software"),     ║
║   to deal in the Software without restriction, including without limitation        ║
║   the rights to use, copy, modify, merge, publish, distribute, sublicense,         ║
║   and/or sell copies of the Software, and to permit persons to whom the Software   ║
║   is furnished to do so, subject to the following conditions:                      ║
║                                                                                    ║
║   The above copyright notice and this permission notice shall be included in       ║
║   all copies or substantial portions of the Software.                              ║
║                                                                                    ║
║   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,                  ║
║   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES                  ║
║   OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.        ║
║   IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY             ║
║   CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,             ║
║   TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE       ║
║   OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                    ║
║                                                                                    ║
╚════════════════════════════════════════════════════════════════════════════════════╝
 */

#ifndef __com_sun_star_logging_XLoggerPool2_idl__
#define __com_sun_star_logging_XLoggerPool2_idl__

#include <com/sun/star/logging/XLoggerPool.idl>
#include <com/sun/star/logging/XLogger2.idl>
#include <com/sun/star/util/XModifyListener.idl>


module com { module sun { module star { module logging {

interface XLoggerPool2 : com::sun::star::logging::XLoggerPool
{

    /** get a localized logger from the pool.

        @param Name
            the name of the logger

        @param Url
            the location of the resource file

        @param Basename
            the base name of the resource file
    */
    com::sun::star::logging::XLogger2 getLocalizedLogger([in] string Name,
                                                         [in] string Url,
                                                         [in] string Basename);

    /** retrieves all logger names
    */
    sequence<string> getLoggerNames();

    /** retrieves filtered logger names (ie: all logger names which starts with filter)
    @param Filter
           the filter (to be retrieved le logger name must start with the filter)
    */
    sequence<string> getFilteredLoggerNames([in] string Filter);

    /** add a modify listener to the pool.

    @param Listener
            the listener that will be notified when a new logger is requested or released from the pool
    */
    void addModifyListener([in] com::sun::star::util::XModifyListener Listener);

    /** remove a modify listener from the pool.

        @param Listener
            the listener which will be removed from the pool
    */
    void removeModifyListener([in] com::sun::star::util::XModifyListener Listener);


};

}; }; }; };


#endif

