/*
╔════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                    ║
║   Copyright (c) 2020 https://prrvchr.github.io                                     ║
║                                                                                    ║
║   Permission is hereby granted, free of charge, to any person obtaining            ║
║   a copy of this software and associated documentation files (the "Software"),     ║
║   to deal in the Software without restriction, including without limitation        ║
║   the rights to use, copy, modify, merge, publish, distribute, sublicense,         ║
║   and/or sell copies of the Software, and to permit persons to whom the Software   ║
║   is furnished to do so, subject to the following conditions:                      ║
║                                                                                    ║
║   The above copyright notice and this permission notice shall be included in       ║
║   all copies or substantial portions of the Software.                              ║
║                                                                                    ║
║   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,                  ║
║   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES                  ║
║   OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.        ║
║   IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY             ║
║   CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,             ║
║   TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE       ║
║   OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                    ║
║                                                                                    ║
╚════════════════════════════════════════════════════════════════════════════════════╝
 */

#ifndef __com_sun_star_ucb_XRestIdentifier_idl__
#define __com_sun_star_ucb_XRestIdentifier_idl__

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/ucb/XRestDataBase.idl>
#include <com/sun/star/ucb/XRestUser.idl>
#include <com/sun/star/auth/XRestKeyMap.idl>
#include <com/sun/star/ucb/XSimpleFileAccess.idl>
#include <com/sun/star/sdbc/XPreparedStatement.idl>
#include <com/sun/star/ucb/ContentInfo.idl>
#include <com/sun/star/uri/XUriReference.idl>

module com { module sun { module star { module ucb {

interface XRestIdentifier: com::sun::star::uno::XInterface
{

    boolean isInitialized();
    void initialize([in] ::com::sun::star::ucb::XRestDataBase DataBase);
    boolean isRoot();
    boolean isFolder();
    boolean isValid();
    ::com::sun::star::uri::XUriReference getUri();
    ::com::sun::star::ucb::XRestIdentifier createNewIdentifier([in] string ContentType);
    ::com::sun::star::uno::XInterface getContent();
    ::com::sun::star::sdbc::XPreparedStatement getFolderContent([in] ::com::sun::star::auth::XRestKeyMap Content);
    string getDocumentContent([in] ::com::sun::star::ucb::XSimpleFileAccess Sf,
                              [in] ::com::sun::star::auth::XRestKeyMap Content,
                              [out] long Size);
    void insertNewContent([in] ::com::sun::star::uno::XInterface Request,
                          [in] ::com::sun::star::auth::XRestKeyMap Content);
    void setTitle([in] string Value);
    sequence<::com::sun::star::ucb::ContentInfo> getCreatableContentsInfo();

    [attribute, readonly] ::com::sun::star::ucb::XRestUser User;
    [attribute, readonly] ::com::sun::star::auth::XRestKeyMap MetaData;
    [attribute, readonly] string Id;
    [attribute, readonly] string ParentId;
    [attribute, readonly] string ParentURI;
    [attribute, readonly] boolean IsNew;

};

}; }; }; };

#endif
