/*
╔════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                    ║
║   Copyright (c) 2020 https://prrvchr.github.io                                     ║
║                                                                                    ║
║   Permission is hereby granted, free of charge, to any person obtaining            ║
║   a copy of this software and associated documentation files (the "Software"),     ║
║   to deal in the Software without restriction, including without limitation        ║
║   the rights to use, copy, modify, merge, publish, distribute, sublicense,         ║
║   and/or sell copies of the Software, and to permit persons to whom the Software   ║
║   is furnished to do so, subject to the following conditions:                      ║
║                                                                                    ║
║   The above copyright notice and this permission notice shall be included in       ║
║   all copies or substantial portions of the Software.                              ║
║                                                                                    ║
║   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,                  ║
║   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES                  ║
║   OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.        ║
║   IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY             ║
║   CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,             ║
║   TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE       ║
║   OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                    ║
║                                                                                    ║
╚════════════════════════════════════════════════════════════════════════════════════╝
 */

#ifndef __com_sun_star_ucb_XRestUser_idl__
#define __com_sun_star_ucb_XRestUser_idl__

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/ucb/XRestDataBase.idl>
#include <com/sun/star/ucb/XRestProvider.idl>
#include <com/sun/star/sdbc/XDataSource.idl>
#include <com/sun/star/auth/XRestKeyMap.idl>

module com { module sun { module star { module ucb {

interface XRestUser: com::sun::star::uno::XInterface
{

    boolean isValid();
    void setDataBase([in] ::com::sun::star::sdbc::XDataSource DataSource,
                     [in] string Password,
                     [in] ::com::sun::star::uno::XInterface Sync);
    string getCredential([inout] string Password);

    [attribute, readonly] ::com::sun::star::ucb::XRestProvider Provider;
    [attribute, readonly] ::com::sun::star::uno::XInterface Request;
    [attribute, readonly] ::com::sun::star::auth::XRestKeyMap MetaData;
    [attribute, readonly] ::com::sun::star::ucb::XRestDataBase DataBase;
    [attribute, readonly] string Id;
    [attribute, readonly] string Name;
    [attribute, readonly] string RootId;
    [attribute, readonly] string RootName;
    [attribute, readonly] string Token;

};

}; }; }; };

#endif
