#ifndef __com_sun_star_ucb_XRestContent_idl__
#define __com_sun_star_ucb_XRestContent_idl__

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/ucb/XRestIdentifier.idl>
#include <com/sun/star/auth/XRestKeyMap.idl>

module com { module sun { module star { module ucb {

interface XRestContent: com::sun::star::uno::XInterface
{

    [attribute, readonly] ::com::sun::star::ucb::XRestIdentifier Identifier;
    [attribute, readonly] ::com::sun::star::auth::XRestKeyMap MetaData;
    [attribute, readonly] boolean IsDocument;
    [attribute, readonly] boolean IsFolder;
    [attribute, readonly] boolean CanAddChild;

};

}; }; }; };

#endif
