#ifndef __com_sun_star_ucb_RestProvider_idl__
#define __com_sun_star_ucb_RestProvider_idl__

#include <com/sun/star/lang/XServiceInfo.idl>
#include <com/sun/star/ucb/XRestProvider.idl>

module com { module sun { module star { module ucb {

service RestProvider
{

    interface ::com::sun::star::lang::XServiceInfo;
    interface ::com::sun::star::ucb::XRestProvider;

};


}; }; }; };

#endif
