#ifndef __com_sun_star_ucb_XRestDataSource_idl__
#define __com_sun_star_ucb_XRestDataSource_idl__

#include <com/sun/star/uno/XInterface.idl>
#include <com/sun/star/ucb/XRestDataBase.idl>
#include <com/sun/star/ucb/XRestProvider.idl>

module com { module sun { module star { module ucb {

interface XRestDataSource: com::sun::star::uno::XInterface
{

    boolean isValid();
    ::com::sun::star::uno::XInterface getUser([in] string Name,
                                              [in] string Password);
    ::com::sun::star::uno::XInterface getRequest([in] string Name);

    [attribute, readonly] ::com::sun::star::ucb::XRestProvider Provider;
    [attribute, readonly] ::com::sun::star::ucb::XRestDataBase DataBase;
    [attribute, readonly] string Error;

};

}; }; }; };

#endif
